(package "psysh"
         "0.1.1"
         "PsySH, PHP interactive shell (REPL)")

(website-url "https://github.com/emacs-php/psysh.el")
(keywords "processes" "php")

(package-file "psysh.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source 'gnu)
(source 'melpa)

(depends-on "emacs" "24.3")
(depends-on "s")
(depends-on "php-runtime")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
